on:
  schedule:
    - cron: '29 23 * * *'
  workflow_dispatch:

name: update_data

jobs:
  update_data:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      # - uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     cache: false
      #     extra-packages: |
      #       ropensci/piggyback
      #       pkgload
      #       tonyelhabr/valorantr
      #       
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("remotes", "dplyr", "purrr", "qs", "curl", "jsonlite", "rlang", "pkgload"))'
      - name: Install GitHub dependencies
        run: Rscript -e 'remotes::install_packages("tonyelhabr/valorantr", "ropensci/piggyback")'
        
      - name: Update Valorant data
        run: Rscript -e 'source("scripts/update-data.R")'
